services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fashion_bot
    ports:
      - "5432:5432"
    volumes:
      - fashion_bot_pg:/var/lib/postgresql/data

volumes:
  fashion_bot_pg: